[merge-tools.diffconflicts]
program = "nvim"
merge-args = ["-c", "JJDiffConflicts", "$output"]
merge-tool-edits-conflict-markers = true

[ui]
editor = "nvim"
merge-editor = "diffconflicts"

[aliases]
ut = ["upload", "@-"]
